#server:
#  port: 8999
#  
#eureka:
# instance:
#  hostname: localhost
#  
#spring:#  application:#    name: api-gateway
#  cloud:
#   gateway:
#    routes:
#      - id: agent-service
#        uri: lb://agent-service
#        predicates:
#          - Path=/agent/**
#      - id: client-service
#        uri: lb://client-service
#        predicates:
#          - Path=/client/**    
#   #         